name: repro

on:
  push:
  
jobs:
  repro:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
    
#       - uses: crazy-max/ghaction-setup-docker@v1
    
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
     
      - run: sudo apt-get install -y socat

      - run: |
          set -eux
          
          sudo socat -d -d -t100 -lf /dev/stdout -v UNIX-LISTEN:/var/run/docker.debug,mode=777,reuseaddr,fork UNIX-CONNECT:/var/run/docker.sock &
          
          docker version >> output.log
          sam --version >> output.log
          
          DOCKER_HOST=unix:///var/run/docker.debug sam build >> output.log
          echo $?
          
          sleep 1
          cat output.log
          
