name: repro

on:
  push:
  
jobs:
  repro:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
    
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - run: |
          set -eux
          
          docker version
          sam --version
          
          sam build
          echo $?
