name: repro

on:
  push:
  
jobs:
  repro:
    runs-on: ubuntu-latest

    steps:
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - run: |
          set -eux
          sam --version
          sam build
          echo $?